name: medqa
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - pip
  - pip:
    - openai
    - faiss-cpu
    - datasets
    - huggingface_hub
    - tqdm
    - requests